backend:
  name: github
  repo: BLodaya/straits-blog # Replace with your GitHub repo
  branch: main
  auth_type: implicit
  app_id: hJhl5DJrSp3jJxBCgSNkIBMeYoTl8anL # Replace with your Auth0 Client ID
  auth_endpoint: /api/auth

media_folder: "public/images/posts" # Folder where media files will be stored
public_folder: "/images/posts" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../../layouts/BaseLayout.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Cover Image", name: "image", widget: "object", fields: [
          {label: "Image URL", name: "url", widget: "string"},
          {label: "Image Alt Text", name: "alt", widget: "string"}
        ]}
      - {label: "Body", name: "body", widget: "markdown"}